allowBuilds:
  '@firebase/util': set this to true or false
  isolated-vm: set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
  puppeteer: set this to true or false
  unrs-resolver: set this to true or false
